### ISSUE TITLE
Why is ID required on the element?

### ISSUE THREAD

**Issue by mhsivitz** [IamAdamJowett/angular-click-outside#1]
Awesome directive! It was exactly what I was looking for. 

I noticed that it won't work properly unless you assign an id to the element. Is there a reason you made this a requirement? Any way to remove this restriction. 

Cheers

**Comment by IamAdamJowett** [comment]
The id is used in the checking for exceptions, which is done on an ID basis, so you want the element to be included in that check. Please feel free to issue a suggested fix though, more than happy to see it improve.
