### ISSUE TITLE
Uncaught TypeError: classNames.indexOf is not a function

### ISSUE THREAD

**Issue by FDiskas** [IamAdamJowett/angular-click-outside#10]
Version 1.1.0
I'm using this version because its much faster then over releases.
![selection_046](https://cloud.githubusercontent.com/assets/468006/9435304/4b8034de-4a4f-11e5-8c5e-0e530245a6ab.png)

**Comment by IamAdamJowett** [comment]
@FDiskas you'll need to change this:

I would change:

    var classNames = element.className;

to 

    var classNames = element.className || []

to get around if you have no classes assigned to the element.

**Comment by SenHeng** [comment]
```
var classNames = element.className || [];
```

I'm using version 2.1.0 and doing the above doesn't solve the bug.
