### ISSUE TITLE
Version 2 - laggy

### ISSUE THREAD

**Issue by FDiskas** [IamAdamJowett/angular-click-outside#11]
There an delay about 1 or 2 seconds on big project then clicking no mater where. Looks like its freeze on click.
Please review and optimize your script.

**Comment by FDiskas** [comment]
This version is faster https://github.com/IamAdamJowett/angular-click-outside/blob/1.1.0/clickoutside.directive.js

**Comment by IamAdamJowett** [comment]
I'll look into this @FDiskas. The main change from v1 to v2 is the use of $parse to remove the need for isolated scope. Perhaps there is an issue around that change.

**Comment by devm33** [comment]
Just to throw in my two cents here, I agree the parse could be problematic. I wonder if doing this lazily could improve performance -- something like waiting until the first time that you need to call the clickOutside to parse it from the attribute. Also moving from link to compile might offer some savings.

From my use case of having many elements on the page that I want to check if they're clicked outside of but only care about any one when it's selected I think a big performance gain could be seen by using a service/factory to listen once to the `$document.on('click'` and then individual directives can save some cycles by registering/deregistering when active/inactive respectively.

Of course I understand that sufficiently diverges from your idea for this plugin though. But if not let me know if you'd be open to a PR to this effect.

**Comment by twhitbeck** [comment]
Out of curiosity, @FDiskas could you try [twhitbeck/angular-click-outside](https://github.com/twhitbeck/angular-click-outside) and see if it fares any better?

**Comment by KamBha** [comment]
I am having the same problem.  I commented out these lines:-
```javascript
if(angular.element(elem).hasClass("ng-hide")){
    return;
}
```

And immediately, the performance improved.  I don't know why, but this *looks* like the problem for me.

**Comment by KamBha** [comment]
And before anyone asks, I have no idea why.

**Comment by IamAdamJowett** [comment]
@devm33 the $parse is now being set on demand as suggested to try to help with the performance. @KamBha that seems odd, that check needs to be done though, and I can't think of another way to do it.
