### ISSUE TITLE
Namespaced events doesn't work without jquery

### ISSUE THREAD

**Issue by marcin-wosinek** [IamAdamJowett/angular-click-outside#13]
The events listner is registerd with:

```
$document.on('click.outsideDirective', function() {/**/})
```

the click event is ignored in case when we use angular without jquery.

**Comment by marcin-wosinek** [comment]
for others with the same issue - downgrade to 2.0.1 makes a trick as well

**Comment by devm33** [comment]
@marcin-wosinek looks like your PR was merged. Should this ticket be closed?

**Comment by marcin-wosinek** [comment]
yes, you are right:)
