### ISSUE TITLE
Document outside-if-not with classes

### ISSUE THREAD

**Issue by danielo515** [IamAdamJowett/angular-click-outside#18]
Hello,

I don't know if this was intended, but for me is perfect. `outside-if-not worksp` with classes as it works with IDs. It's a very great feature, because all my buttons has the class `btn`. I just tried and it worked, but there is nothing on the documentation that teaches about this.

Regards

**Comment by IamAdamJowett** [comment]
@danielo515 the README.md now has a small mention of classes as suggested. Thanks for the tip.
