### ISSUE TITLE
Problems with scope

### ISSUE THREAD

**Issue by koorb** [IamAdamJowett/angular-click-outside#2]
Hi – as far as I can see I've set it up fine, and things are logged when I 'click outside' but it doesn't seem to be affecting the original scope at all. Any thoughts?

Here is a pull out of my code, hope it makes sense – http://jsbin.com/dowijacati/2/edit?html,js,output

**Comment by IamAdamJowett** [comment]
Hi @koorb ,

There are two issue that causes this that I can see. The first is that the scope variable is being updated, but without a $digest cycle being run (or perhaps before, I can never tell with Angular). You can overcome this with a $scope.$evalAsync call to ensure it happens.

The second is that the element you have the directive on should have an id assigned to it if you don't want it to be included (as per outside-if-not attribute).

Here is an update on your code sample to show what I mean:

http://jsbin.com/hokapefehi/4/

Hope that helps mate.
