### ISSUE TITLE
Handle touch event on mobile device?

### ISSUE THREAD

**Issue by MKDonovan** [IamAdamJowett/angular-click-outside#20]
Is the current implementation intended to handle touch events on mobile devices?

**Comment by sitedisks** [comment]
I found for the iPad is document event should be 'touchstart' not 'click'. As below: 

var ua = navigator.userAgent,
event = (ua.match(/iPad/i)) ? "touchstart" : "click";
$document.on(event, eventHandler);

**Comment by IamAdamJowett** [comment]
This is a good point, I am working on a solution in the next version that will cover this as well as touch screen desktop computers as well.

**Comment by IamAdamJowett** [comment]
@sitedisks touch screen support has been added to release 2.3.1
