### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by tobiasbueschel** [IamAdamJowett/angular-click-outside#21]
Hi nice plugin but I haven't been very lucky implementing it (yet)! I included the directive as described but it's not working on my code for some reason:

My code: https://gist.github.com/tobiasbueschel/ed257bb37d16bc85cacb

any ideas?

**Comment by IamAdamJowett** [comment]
Hard to tell @tobiasbueschel without looking at your controller, can you share the function in the controller that is being called?
