### ISSUE TITLE
Not compatible IPad touch

### ISSUE THREAD

**Issue by sitedisks** [IamAdamJowett/angular-click-outside#23]
Works prefect but not iPad safari. Obviously it not recognizes the $document.on('click') event. My solution was detect it iPad then 'touchstart'. As below:

var ua = navigator.userAgent,
      event = (ua.match(/iPad/i)) ? "touchstart" : "click";
$document.on(event, eventHandler);

**Comment by IamAdamJowett** [comment]
Thanks for the tip @sitedisks, if you would like to issue a pull request with that fix I can bring it in that way, else I will add it to the list of fixes for the next version.

**Comment by sitedisks** [comment]
No worries, @IamAdamJowett Just add touch features in your next release through. Cheers.

**Comment by IamAdamJowett** [comment]
Duplicate of https://github.com/IamAdamJowett/angular-click-outside/issues/20
