### ISSUE TITLE
Prevents inner href's from working

### ISSUE THREAD

**Issue by tandrewnichols** [IamAdamJowett/angular-click-outside#24]
If you put `click-outside` on something that (for example) opens a dropdown, and that dropdown contains links with hrefs, those hrefs don't navigate (unless they only change the hash). E.g.

```html
<li id="something-in-menu" click-outside="showDropdown = false">
  <a href="#" ng-click="showDropdown = true">Click here</a>
  <div ng-show="showDropdown">
    <ul id="submenu">
      <li><a href="/this/link/no/worky">Doesn't work</a></li>
      <li><a href="/blah#!/this/does">But only if you're already on /blah#!</a></li>
    </ul>
  </div>
</li>
```

**Comment by elkhorn360** [comment]
This might help you 

 var eventHandler = function(e) {
                    //check the element is an anchor
                    if(e.target.tagName.toLowerCase() === 'a'){
                      return
                    }

**Comment by IamAdamJowett** [comment]
@tandrewnichols testing this locally, all seems to work fine. I have added you example code to a jsfiddle and it seems to work ok: https://jsfiddle.net/iamadamjowett/7tdq66eq/
