### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bateGit** [IamAdamJowett/angular-click-outside#26]
`<div id="J_div"></div>`
`<div id="J_div_1"></div>`
`<div id="J_div_2"></div>`
`(id !== undefined && id.indexOf(classList[i]) > -1) || (classNames && classNames.indexOf(classList[i]) > -1)`

Fix
`(id !== undefined && id === classList[i]) || (classNames && classNames === classList[i])`

**Comment by IamAdamJowett** [comment]
Thanks, implemented into 2.2.2 release today.
