### ISSUE TITLE
Publish to NPM registry

### ISSUE THREAD

**Issue by yasnov-d** [IamAdamJowett/angular-click-outside#27]
Could you please publish your module to NPM registry for npm/webpack users? I'm not using bower.

**Comment by AOlefirenko** [comment]
+1

**Comment by Ilya93** [comment]
+1

**Comment by IamAdamJowett** [comment]
At the moment I can't do a straight publish of this repo due to another angular-click-outside existing on the npm registry. Will look at a new naming convention to counter this in the future.

**Comment by AOlefirenko** [comment]
@IamAdamJowett you can just use your own scope  https://docs.npmjs.com/misc/scope https://docs.npmjs.com/misc/scope

**Comment by IamAdamJowett** [comment]
@yasnov-d @Ilya93 @AOlefirenko

All done, thanks for the tip, you can find it here: https://www.npmjs.com/package/@iamadamjowett/angular-click-outside
