### ISSUE TITLE
Consider removing isolated scope

### ISSUE THREAD

**Issue by elado** [IamAdamJowett/angular-click-outside#3]
Can't apply on element that already asks for isolated scope.
Functions can be extracted with `$parse`. See http://luxiyalu.com/angular-directive-click-elsewhere/

**Comment by IamAdamJowett** [comment]
Worth considering @elado for sure, will look into it shortly.

**Comment by elado** [comment]
Check out https://github.com/TheSharpieOne/angular-off-click

**Comment by IamAdamJowett** [comment]
@elado this has been implemented in the latest version. Thanks for the suggestion.
