### ISSUE TITLE
Console logs

### ISSUE THREAD

**Issue by ntopulos** [IamAdamJowett/angular-click-outside#30]
When I use the plugin, it logs some tests results in the console:

> passed the hide test
> passed the event check
> about to check
> about to check

Is it normal? How can I disable this behaviour?
Thanks, and very useful package by the way!

**Comment by IamAdamJowett** [comment]
Hey @ntopulos I would suggest to upgrade to 2.5.0 which has removed these and also has some other bug fixes: https://github.com/IamAdamJowett/angular-click-outside/releases/tag/v2.5.0

You could also upgrade via bower or npm if that is your choice of installation.
