### ISSUE TITLE
[BUG] Input type file will not trigger

### ISSUE THREAD

**Issue by naokha** [IamAdamJowett/angular-click-outside#32]
Using this directive, if you have an input of type file on your document, the file browser won't open.
As a workaround, I added the following lines in the beginning of the eventHandler function (it can be improved) :
`
if(e.target.type === "file") {
    return;
}`

**Comment by ablamunits** [comment]
+1, this is happening, and I was able to resolve it with the above method, however only when using version `2.5.0`. With the latest version, this did not work for me.

@naokha what version are you using?

**Comment by IamAdamJowett** [comment]
@naokha @ablamunits I am not seeing this behaviour in the latest version with file inputs in the document, inside the element with the directive applied or combinations of both. 

Can you clarify the structure or perhaps get up a jsfiddle or plunkr so I can see the exact scenario you mean. Browser details might be handy as well.

**Comment by IamAdamJowett** [comment]
@ablamunits I have updated the example with a file input to demonstrate how it works.
