### ISSUE TITLE
Comma Separated Values

### ISSUE THREAD

**Issue by Elegant-Bird** [IamAdamJowett/angular-click-outside#39]
You should add to the ReadMe that the values that are comma separated cannot contain any spaces. I didn't realize that you weren't doing a trim on the directives and spent hours just realized that the spaces were be added to the class names, which of course won't work.

**Comment by IamAdamJowett** [comment]
@Elegant-Bird this isn't true, classes can be separated by commas, and can contain a space after the comma as well. Perhaps this is a part of a bug where having more than two classes was causing things to fail? This has been fixed in the recent release v2.8.2 5c64f22
