### ISSUE TITLE
Outside if not doesn't work with class if element has several classes

### ISSUE THREAD

**Issue by lamigue** [IamAdamJowett/angular-click-outside#41]
L54:
`                                if ((id !== undefined && id === classList[i]) || (classNames && classNames === classList[i])) {
                                    // now let's exit out as it is an element that has been defined as being ignored for clicking outside
                                    return;
                                }`

ClassNames is a string with all the classes of an element while classList represents only the class you want to exclude. First you have to split classNames : 
`classNames.split(' ')`

And after you have to compare each element of classList with each element of this new list. 

Example:

`var listClassNames = classNames.split(' ');
for(var j = 0; j< listClassNames.length; j++){
    if(classList[i] === listClassNames[j]){
        return;
    }
}`

**Comment by IamAdamJowett** [comment]
Thank for spotting this @lamigue, this has been address in the most recent 2.8.2 version 5c64f22
