### ISSUE TITLE
Could be used on a SELECT with it's options ?

### ISSUE THREAD

**Issue by ianjohnspain** [IamAdamJowett/angular-click-outside#48]
Hi,

Do you know if this can work with a SELECT and its options.

I am using the ng-options to fill the contents.

I would like to get some kind of visual feedback and expand / collapse. Actually, expand isn't needed as i can use a click of the button above. BUT collapse is, currently i have been able to use ng-blur but you have to completely click off the element for it to be called.

Is this something that is supported ?

I did check the issues here to see if anyone else was trying to achieve the same thing but couldn't find anything 

Thanks

**Comment by IamAdamJowett** [comment]
Hey mate, are you meaning clicking outside a particular option within that select rather than clicking outside of the select itself? 

This sounds like something that could be handled via ng-change and a controller function but perhaps I am completely misinterpreting?
