### ISSUE TITLE
Update the module name

### ISSUE THREAD

**Issue by eyalcohen4** [IamAdamJowett/angular-click-outside#51]
The readme file said - add 'angular-click-outside' module, which not work.

instead, the updated readme file after install it and watch in the node_modules, said to include the work module name - 'tw.directives.clickOutside'

please update this for not confuse some people.
tnx

**Comment by IamAdamJowett** [comment]
Hey @eyalcohen4 it looks like you are using a different directive, namely this one: https://github.com/twhitbeck/angular-click-outside not mine.

To install mine via npm, make sure you qualify it with my username `npm install @iamadamjowett/angular-click-outside`
