### ISSUE TITLE
Release with updated module name

### ISSUE THREAD

**Issue by marcin-wosinek** [IamAdamJowett/angular-click-outside#7]
Hello;
Thanks a lot for sharing the module.

I've just noticed that the version installed by default by bower has a different module name. Would it be possible to release the updated version?

**Comment by IamAdamJowett** [comment]
Thanks for picking that up @marcin-wosinek. A new bower install angular-click-outside should bring down v1.1.5 which has the new module name.

**Comment by marcin-wosinek** [comment]
yay, thanks a lot:)
