### ISSUE TITLE
Error: [$injector:nomod] Module 'mouse.utils'

### ISSUE THREAD

**Issue by FDiskas** [IamAdamJowett/angular-click-outside#8]
the 1.1.5 version has some dependencies your missing something

**Comment by FDiskas** [comment]
So you changed the module name and this is still minor release?
I updated my project using bower 
`"angular-click-outside": "~1.1.0",`
and this should not broke my entire project :)

**Comment by FDiskas** [comment]
`Error: [$rootScope:inprog] $apply already in progress` - no I can't use jquery date picker with manual scope apply.
```
onSelect: function (date) {
                                scope.$apply(function () {
                                    ngModelCtrl.$setViewValue(date);
                                    scope.$parent.setCurrDate();
                                });
                            }
```

**Comment by IamAdamJowett** [comment]
@FDiskas yep good point, will look into how I can rectify the semantic versioning on this.

**Comment by IamAdamJowett** [comment]
Should be fixed now, check releases: https://github.com/IamAdamJowett/angular-click-outside/releases
